---
language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0" TRUSTED_NODE_DATA="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7.0" TRUSTED_NODE_DATA="yes"
notifications:
  email: false
